language: node_js
sudo: false
node_js:
- 5.3

cache:
  directories:
    - node_modules
    - bower_components

env:
  matrix:
  - JOB=unit
  - JOB=e2e BROWSER=chrome
  - JOB=e2e BROWSER=firefox VERSION=34
  global:
  - LOGS_DIR: /tmp/sauce-build/logs
addons:
  sauce_connect:
    username: macgyver-ci
    access_key: 5aa3c19a-1374-439d-8777-cfd7521eb740
before_script:
  - ./misc/travis/before_build.sh
script:
  - ./misc/travis/run.sh
after_script:
  - ./misc/travis/print_logs.sh
